developers_get_by_level:
  path:       /api/v1/developers/{level}
  controller: App\Controller\DeveloperController::level
  methods:    GET|HEAD

fetch_tasks:
  path:       /api/v1/tasks/fetch
  controller: App\Controller\TaskController::fetch
  methods:    POST

match_tasks:
  path:       /api/v1/tasks/match
  controller: App\Controller\MatchTaskController::match
  methods:    POST

match_tasks_get:
  path:       /api/v1/tasks
  controller: App\Controller\MatchTaskController::index
  methods:    GET
